[package]
name = "rvasm"
version = "0.1.0"
authors = ["Jakub Szewczyk <kubasz51@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "0.6.10"
structopt = "0.2.18"
toml = "0.5.1"
